### ISSUE TITLE
enforce referential integrity

### ISSUE THREAD

**Issue by twhiteaker** [lter/LTER-core-metabase#13]
We should make sure we enforce referential integrity for tables related to lookup tables. I think this would cause the database engine to raise an error if you entered a NameID in the DataSetPersonnel table that didn't already exist in the People table, for example, which could help prevent loading invalid data.

**Comment by scelmendorf** [comment]
I agree with this. FWIW I've been using the email as the nameID/pkey on people because it allows people to fill out their own metadata template more easily w/o needing to know database IDs. I guess this is a bad idea if we want a single person to have metadata with two different physical addresses under the same email address but this seemed very edge case to me.

**Comment by mobb** [comment]
agreed - that is an expectation of any decent model. I hope the pre-distribution you got was not missing its foreign keys. Is it possible you did not load (or get) the constraints?  Gastil is picking up the disc on slack - which is a better place for chatting

**Comment by mobb** [comment]
non-issue.
