### ISSUE TITLE
enforce order of dataset creators?

### ISSUE THREAD

**Issue by twhiteaker** [lter/LTER-core-metabase#14]
I think @lkuiucsb's workflow is to enter the organization (e.g., SBC LTER) as the first creator of a given dataset. I couldn't find evidence that this is required in EML documentation, but maybe I missed it. If it's required, should we somehow require that in the schema (I don't know if that's possible) or let the R scripts work it out?

**Comment by scelmendorf** [comment]
I think the workflow is to enter the organization as one contact for a given dataset, not creator? I do think it's useful to have the IM (alias email) as an alternate contact for each dataset, since people move/leave.

**Comment by mobb** [comment]
Hi @twhiteaker  - the recommendation from LTER is that the site be the first creator, yes. But it is not required by EML generally, and there are datasets that an LTER site manages that do not have the site as a creator. (e.g., SBC LTER has some fire perimeters in our watersheds that we republished from USGS. SBC LTER is not the creator). So there is no repository check written for that metadata either. 
 
If you want to control the output from metabase in an EML record (e.g., to send yourself a reminder) probably the best place to check for that is in the export layer (the R-code).

**Comment by twhiteaker** [comment]
@mobb Is there a formal guidelines document somewhere that states that the site should be the first creator? It'd be nice if such guidelines were in one place so that folks like me don't have to rely on stumbling upon best practices by word of mouth.  I looked for in the [EML BP](https://environmentaldatainitiative.org/2018/02/16/eml-best-practices-v-3/), but it just recommends using organization or PI as one of the creators and doesn't specify an order.

**Comment by mobb** [comment]
@twhiteaker the answer to that is actually pretty long (sorry) - 
Because there is a difference between what we call "BP for EML" (what EDI is promoting), what LTER might want to see in its sites' EML metadata (what you are looking for). It gets more complex when we start considering how `eml:eml/dataset/creator` element gets used  -- e.g., constructing a citation (author order implies intellectual contribution -- does an org contribute to that or just the people? when does it matter?)

There are bigger groups talking about this (http://commons.esipfed.org/node/308), and there are obvious implications for what we put in metadata. So I think its a good idea for EDI to expand its general recommendations. (the citation recommendations seem to undergoing review right now)

The EML BP v3 doc already includes some LTER-specific preferences (which are in separate sections). that was actually a unilateral decision, because we wanted to get that doc generalized really fast. There may be a few of those LTER-specific bits that should be reconsidered (e.g., they are now out of date); maybe this is a good time.

I created a new issue here: https://github.com/EDIorg/dm-best-practices/issues/22

**Comment by twhiteaker** [comment]
`vw_eml_creator` (and `vw_eml_associatedparty`) does order by the `AuthorshipOrder` column, so as far as this project is concerned, this issue was already resolved.  It's up to the client code to honor the order in the view when generating EML.
