### ISSUE TITLE
Address entity-level converage inconsistencies

### ISSUE THREAD

**Issue by twhiteaker** [lter/LTER-core-metabase#20]
By virtue of its name, I presume `DataSetSites` refers to site coverage for the dataset rather than per entity within the dataset. However, it has an `EntitySortOrder` column, which implies that sites are specified per entity. Similarly, `DataSetTemporal` has `EntitySortOrder`.  The views, `vw_eml_geographiccoverage` and `vw_eml_temporalcoverage` both include `entity_position`.  

So, we should decide whether we will support entity-level coverage in metabase, and if necessary adapt the schema and views accordingly.  Gastil seldom uses entity level coverage elements at her site.

Historical note: In the original Metabase, the table `DataSetSites` does not have an `EntitySortOrder` column. (Whereas `DataSetEntitySites` does.)

**Comment by scelmendorf** [comment]
FWIW, I don't think it's that common to use entity level coverage either. But I do think it is useful to have  a set of geographic coverages per dataset (otherwise with distributed datasets the bounding box gets huge). I generally don't bother splitting up the temporal coverage into subsets (i.e. for a dataset that was collected 1997 and 2001 I would just make the temporal coverage 1997-2001). I think(?) perhaps the entity sort order not actually meant to be datasetentities, but rather index 1 or more coverages within a dataset?

**Comment by mobb** [comment]
>  I think(?) perhaps the entity sort order not actually meant to be datasetentities, but rather index 1 or more coverages within a dataset?

in other instances of metabase, we have used entity-level coverage, although it is somewhat uncommon (across the network). This table allows that, and this is what how entitysortorder is intended to be used.

**Comment by atn38** [comment]
closing since we decided to keep the convention (0 in EntitySortOrder means dataset level coverage)
only remaining task is to add it to taxa. see #59
