### ISSUE TITLE
entity-level distribution information 

### ISSUE THREAD

**Issue by atn38** [lter/LTER-core-metabase#29]
On same topic as #26 item 11, what's the common usage pattern for entity-level distribution info? 

Right now R code concatenates DataSetEntities.Urlhead and DataSetEntities.FileName to make a download URL. (I'm adding condition to return NULL if Urlhead is NULL.)

If unlike SBC, a site doesn't host data on own site, then perhaps there's no need for entity-level distribution in EML doc?

**Comment by mobb** [comment]
technically, that's true. but I think you might need to have a distribution element of some type (I should confirm that). 
One simple solution is a place holder that will obviously fail, like using http://example.org for the head. (pasta will ignore the URL if you upload from the web interface, so that is the only use-case this would work for)
another more true-to-life (or universal) solution might be appropriate, but will be more complex

**Comment by gastil** [comment]
I had not considered the option of manually attaching the data files along with the EML to submit to PASTA. I've only ever done that for testing that feature itself. But yes I can see if you are working from your desktop not having a url-accessible file. I'll go with Margaret's suggestion but rather than example, Id make up a fictitious URL such as 
http://fake.url.placeholder.edu/ 
so that the next person who comes along and sees it does not just think it is broken. 
Before committing to that, do test it with portal-s. 
Also, isn't info about authentication (or lack thereof) included in the entity-level distribution tree? Or does portal just assume if that is not provided then to default to anonymous access? I like it to be explicit.

**Comment by mobb** [comment]
yes, an access tree is optional under the entity distribution/physical (to override the dataset-level access tree). 
each dataset has its own access rules. No access tree means datasets is not accessible to anyone but the submitter (does NOT default to anon)

**Comment by atn38** [comment]
@gastil I think lots of smaller sites/projects use the manual upload option! At least all the EDI fellows not at UMich (OBFS and other sites) did AFAIK.
