### ISSUE TITLE
Rename EMLUnitDictionary  to UnitDictionary 

### ISSUE THREAD

**Issue by twhiteaker** [lter/LTER-core-metabase#31]
You can add custom units to EMLUnitDictionary, so really it is a unit dictionary if you have added any custom units at all.  And the `custom` attribute could be renamed to `IsEmlUnit`.  See #30 .

**Comment by mobb** [comment]
you're right, that the list of units is a superset of what is included with EML schema (as is true for its parent, EMLUnitType). However, it has fields for STMML descriptions, which is the schema that EML uses, so the EML-moniker is appropriate (or could be STMML- instead). 
This table (and EMLUnitType) will need to be revisited with EML 2.2, because there are some new unit features we may want to take advantage of. A name change (if deemed necessary) could happen then. 

related to https://github.com/EDIorg/unit-registry/
(which has notes about additions specifically to synchronize with EML 2.2)

**Comment by gastil** [comment]
It may be moot whether or not a unit listed in the metabase table EMLUnitDictionary is or is not also offered as a standard unit in EML2.1 or EML2.2, or any version. Looking at the way my table is populated, I have FALSE for the column "custom" for those units which are offered as a standardUnit in EML2.1. (What you suggested above is opposite boolean.) Notice that this depends on the version of EML. If I were designing this table today, I would name the column "standardInVersion" and list the EML version that has that unit as a standardUnit that I prefer to use, leaving it null or entering the word custom if either it is not offered as standard or I do not like how it is offered as standard.

**Comment by atn38** [comment]
closing, EMLUnitDictionary is called the same in latest round of table renaming. See commit a477c52bfe69f7c3b4152995a37c0e28b900ce9d
