### ISSUE TITLE
special characters in SBC sample data

### ISSUE THREAD

**Issue by atn38** [lter/LTER-core-metabase#33]
in 5_load_sample_sbc_datasets.sql, adding rows to DataSetAttributes, there's this attribute description: 

`Total number of fronds &gt;1 m in length on the plant.`

which comes out in EML as ` Total number of fronds &amp;gt;1 m in length on the plant.`

--
If the row is edited manually in DBeaver to

`Total number of fronds > 1 m in length on the plant.`

then it comes out in EML as `Total number of fronds &gt; 1 m in length on the plant.` which is correct.

-- 
I don't know what's the fix for this would be, or even is a fix is needed. But it does seem XML entity references (eg. `&gt;`) if present in database doesn't get displayed correctly in R-output EML.

**Comment by mobb** [comment]
short answer:
5_load_sample_sbc_datasets.sql is OK as is (with &gt; in place of >). 
so that means: you need to use `&lt;` and `&gt;` for `<` and `>`, respectively 

long answer: 
Greater-than and less-than symbols should always be written as "entity references" when they go into XML. That's because `<` and `>` are the opening/closing symbols for the XML tags themselves.  You actually got lucky -- some XML parsers (Oxygen) will only complain if you use the opening tag (`<`), because anywhere you put `<`, it thinks you are starting a new element. You got lucky in that this was a `>` (closing symbol).  Entity references will be handled correctly, e.g., by a browser displaying the XML as HTML.

Do this experiment: change that `>` to a `<` and see what happens.

Your other option (If you don't like looking at the entity refs in XML), then write it out: 
`number of fronds greater than 1 m in length`

**Comment by atn38** [comment]
Margaret, 

I understand that `<` and `>` has got to be in form `&gt;` and `&lt` for valid XML. 

This is noting that if `&gt;` is present in database then it becomes `&amp;gt;` in R-output XML; while if it's `>` then it becomes `&gt;`. Which is what we want.

**Comment by mobb** [comment]
Sorry - I did not read your example carefully.  The inserted ampersand might be an R-feature - TTBOMK other export methods (or languages) don't alter the content on the way out. 
You are safe leaving your `>` in the db, but watch out for `<`.

**Comment by twhiteaker** [comment]
What @atn38  is suggesting is changing [this line](https://github.com/lter/LTER-core-metabase/blob/master/sql/04_load_sample_sbc_datasets.sql#L810) (and the next one) in 04_load_sample_sbc_datasets.sql so that

`Total number of fronds &gt;1 m in length on the plant.`

becomes

`Total number of fronds >1 m in length on the plant.`

since there is no need to escape the angle bracket on the way in to the database.  In fact, escaping on the way in creates a problem because software is escaping the & on the way out, and thus the greater than sign is lost in renderings of the resulting XML.

**Comment by mobb** [comment]
I understand that, and that substitution will work in this particular case. 
But at the moment I don't agree that the substitution is a general solution - it needs more discussion on what are the responsibilities of the DB and what are the responsibilities of the export-code.  
special characters are a real bugaboo.

**Comment by twhiteaker** [comment]
My two cents on responsibilities:
If it's a UTF-8 character, I think it's fine to put it in the DB (in the context of things like description fields, but we have to be more careful with fields storing filenames for example).  In code, you're typically using an XML library that is smart about escaping special characters when writing XML. Thus, relying on the export code to escape special characters shouldn't require any extra effort.  In fact, it appears that R is already escaping the characters.

**Comment by gastil** [comment]
I'll match your 2 cents and raise you another 2 cents. (That is supposed to sound like playing poker). 
Do not depend on content of text fields to be handled by R or any other single output purpose in mind. That is 'coding to the implementation'. You cannot be sure that attributeDescription will not be used by some other code that has a different encapsulation behavior. For example, the xslt that forms the metadata html pages in portal, over which you have no control. I always spell out 'greater than' or 'less than' and never put angle brackets or other special characters like & that would get encapsulated in my attributeDescriptions. I have seen that double-encapsulation happen all too often.
