### ISSUE TITLE
include more person ID types in VIEWs or possibly delete table Peopleidentification

### ISSUE THREAD

**Issue by atn38** [lter/LTER-core-metabase#35]
vw_eml_creator only pulls column Identificationlink from table lter_metabase.Peopleidentification and assumes it's ORCID. 

```
CREATE VIEW mb2eml_r.vw_eml_creator AS
SELECT i."Identificationlink" AS orcid 
FROM ((lter_metabase."DataSetPersonnel" d LEFT JOIN lter_metabase."People" p 
ON (((d."NameID")::text = (p."NameID")::text))) LEFT JOIN lter_metabase."Peopleidentification" i 
ON (((d."NameID")::text = (i."NameID")::text)));
```

propose to either: 

- ALTER VIEW to allow possible multiple ID types per person

or 

- adopt ORCIDs as ID system of choice, get rid of table Peopleidentification, whose purpose was to allow multiple ID types. plus ADD column "orcid" to table People instead.

**Comment by gastil** [comment]
Can we split these two separate issues? ORCiD is not related to merging creator and associatedParty. Also, the file diff is not useful if it first does a DROP of an existing view then writes a new VIEW. This is a problem of git not being designed for SQL. I suppose we could put the old VIEW in the same file, just to be DROPped. Moot in this instance because I'm not ok with merging creator and associatedParty. 

I would like to see the before/after diff of the VIEWs with ORCiD. Perhaps I can reconstruct that.

**Comment by mobb** [comment]
Along the lines of mapping views to EML names, the column should match the of the element xpath they are going to go into. so
CREATE VIEW mb2eml_r.vw_eml_creator AS
SELECT i."Identificationlink" AS userId 
...
i.IdentificationType AS directory

```
<userId directory="http://orcid.org/">https://orcid.org/0000-0002-8350-3759</userId>
```

**Comment by gastil** [comment]
The text of Margaret's email seems to have gotten clipped, losing a lot.
Instead, look at Issue 35 comment here:
https://github.com/lter/LTER-core-metabase/issues/35

**Comment by atn38** [comment]
closing, pull request #47 resolves this
