### ISSUE TITLE
remove vestigial constraints (e.g. SiteType)

### ISSUE THREAD

**Issue by atn38** [lter/LTER-core-metabase#36]
possibly another multi-entry issue. will update if I stumble across more

1. SiteList.SiteType
`
CONSTRAINT "CK_SiteRegister_SiteType" CHECK ((("SiteType")::text = ANY (ARRAY[('beach'::character varying)::text, ('intertidal'::character varying)::text, ('land'::character varying)::text, ('nearshore'::character varying)::text, ('offshore'::character varying)::text, ('other'::character varying)::text, ('pier'::character varying)::text, ('reef'::character varying)::text])))
`

PROPOSE to create a lter_metabase.SiteType table, so each site can populate with their own CV of site types? Could be overkill for something internal (doesn't appear in EML)

**Comment by gastil** [comment]
Here again, same answer, the full-size Metabase does have a cv parent table for SiteType: SubSiteTypeList. Although I see it is populated with a different vocabulary than the CHECK constraint in mini metabase.

**Comment by gastil** [comment]
If you want to use the same table as full-size Metabase, here is the CREATE statement: 
CREATE TABLE metabase2."SubSiteTypeList"
(
  "SubTypeCode" character varying(10) NOT NULL,
  "SubTypeName" character varying(100) NOT NULL,
  "SubTypeDesc" character varying(250),
  CONSTRAINT "PK_SubSiteCodeList" PRIMARY KEY ("SubTypeCode")
)
Note that my schema name happens to be "metabase2". Substitute appropriately ;)

**Comment by atn38** [comment]
@gastil, not sure if that came across, but I was also questioning if SiteType is necessary in core-metabase! (so this links back to #26 which I'm updating to be more organized).

**Comment by gastil** [comment]
I am not the right one to ask whether SiteType is needed. I do tend to categorize every other thing, but the EML does not make use of SiteType, that I can see. It could help with filtering, for the database user, especially for SBC where they have so many sites and they neatly fall, geographically, into Land, Shore, and Ocean. For MCR, all sites are of SuperType 'unspecified'. So, obviously, Im not the one to ask. @mobb you want to comment?

**Comment by atn38** [comment]
On broader topic of vestigial constraints, this one on `SiteList.ShapeType` is the only other one I can find that we might wish to modify:

`
    CONSTRAINT "CK_SiteRegister_ShapeType" CHECK ((("ShapeType")::text = ANY (ARRAY[('point'::character varying)::text, ('rectangle'::character varying)::text, ('polygon'::character varying)::text, ('polyline'::character varying)::text, ('vector'::character varying)::text]))),
`

**Comment by twhiteaker** [comment]
For SiteType, I suggest we just remove the constraint.  I don't think we need a separate lookup table.

Can we drop ShapeType?  I'm not seeing how that's useful since:

1) We can only store points and rectangles.  Hmm, unless the purpose of this field is to indicate the actual feature's shape type, e.g., a lagoon is a polygon, not a rectangle bounding box.  Or I guess you could include a shapefile as a data entity. But I assume this field is about the shape type as stored in the SiteList table.
2) We can infer whether things are points or rectangles by testing north==south and east==west in the SiteList table.  
3) It's not in EML and I don't know how I'd use the field.

**Comment by gastil** [comment]
I do not use it for MCR but I looked at how SBC uses ShapeType. There, the table is named SiteRegister. The column ShapeType is in the set (point, polygon, poly line, rectangle). My guess is it is used for management (ie for the IM to keep track of things). The four lat,lon point model can only do rectangles but often our sites are other shapes or points. In the EML for MCR, I manually add back in my polygons to the EML because the EML writing program does not handle those. 
======
Geographic location is a whole sub-area of IM. Consider whether you are writing Metabase just for EML or for other uses also. If you already have GIS data stored elsewhere, are you going to sync that with Metabase? Or pull that content separately? Or just use the simple box for the EML? 

Locations ("sites") do tend to be nested in a hierarchy and that is what Wade was modeling with the SubSites and SuperSites. I seen that did not get into mini metabase. The site names tend to carry that information. MCR LTER already had geographic info in the database before metabase so I do not depend on metabase for geographicCoverage other than the simple boxes.

====
SiteType seems simple enough to handle the cv in a CHECK constraint rather than meriting its own cv table. The SiteType seems for the IM, not for the EML, likely used for sorting.

**Comment by twhiteaker** [comment]
ShapeType may be useful if we eventually move beyond points and rectangles, and if we use that GRing pattern.  Side note: If designing from scratch, my preference would be to use a single string field which stores WKT, since that covers both the geometry type and the coordinates, but XML Validation and FGDC and yada yada.  For now, I suggest we at least drop the constraint on ShapeType.

While handling SiteType with a CHECK constraint seems simple, I think it is presumptuous of us to populate the constraint for the end user. I'd rather leave the constraint out and let the end user populate it if desired, similar to how we handle AuthorshipRole.

## Suggested actions:

Drop constraints on ShapeType and SiteType.

**Comment by atn38** [comment]
closing since we removed SiteType constraints in commit 7d5cb17e8ec5145ac5d85929c7134c1c716fc718
