### ISSUE TITLE
multiple missing values per attribute

### ISSUE THREAD

**Issue by scelmendorf** [lter/LTER-core-metabase#38]
I noticed (@atn38 confirms) that multiple missing value codes for a single attribute are not supported by the current schema. I find this comes up all the time (i.e. u= under detection limit, na= lost the sample), and it's super important to document both to distinguish between MCAR vs biased missingness for analysis

**Comment by gastil** [comment]
In MCR datasets we do have multiple missing value codes. Especially for matlab-generated data files we need them for codes such as NaN and Inf. And in the species survey data files the fish length has a different code for "could not see the length" ie an eel in its hole, versus "that year we did not measure length". Multiple missing value codes are essential. We have them in full Metabase. I see mini metabase does not offer that.

**Comment by atn38** [comment]
@gastil, how does full metabase implement multiple missing codes? An additional table? Also agree this feature is essential.

**Comment by twhiteaker** [comment]
[Full metabase online schema is here.](http://gce-lter.marsci.uga.edu/public/resources/erds/GCE_Metabase2_Aug2011.pdf)

**Comment by gastil** [comment]
not a perfect solution, but full metabase has the xml data type for some columns such as missing value, bounds, enumeration, things that can have zero to many sets code-value pairs. I believe mini metabase was trying to avoid the xml data type. The most robust way to model these would be with cross-reference tables because these are many-to-many. A many-to-many at the attribute level uses a 3-part id to specify the column and an id for the (item). (That item could be a missing value, an enumerated code, a bound.) The dataset, entity and attribute form what I call a (di,ei,ai). Here is a case where added complexity better describes the actual data model and to code around that adds unwarranted complication. Margaret and I wrote a databits about that ages ago, Complex vs Complicated. ;)

**Comment by gastil** [comment]
Actually, Tim, that is not what I mean by "full metabase". That is GCE Metabase, the ERD link you posted.
By "full metabase" I mean the version I use and Margaret used before mini metabase. The LTER_core_metabase is closer to mini than full. Wade's GCE Metabase does not use the XML data type. I am not seeing a column named MissingValueCode in Wade's table DataSetVariables, but the column ValueCodes might be it. If so, it may be a comma-separated list. He did use those for putting multiple values in one cell.

**Comment by atn38** [comment]
If I understand you correctly @gastil, a many-to-many solution would involve two additional tables: 
1. a reference table called "EMLMissingValueCodes" with u=under detection limit etc
2. a table called "DataSetMissingValueCodes", using a (di, ei, ai) for key then multiple rows per key for codes used.

This is similar to how sites and keywords are implemented now, which is also many-to-many. If we implement this for core-metabase, I'll look into how R code would handle this to make multiple EML elements. 

@scelmendorf, how do you deal with string-type missing codes in otherwise numeric columns?

**Comment by mobb** [comment]
For those interested, here is a Brief History of Metabase:
https://github.com/mobb/ucsb_metabase_documentation/blob/master/background/metabase_history.md

**Comment by gastil** [comment]
Yes 2 new tables and yes those table names look like the pattern of naming, which is good for consistency. The resemblance to the cross-reference tables for keywords and sites is because those are also many-to-many cross-reference tables. The difference is those are things at the dataset level of EML versus our missing value codes (and bounds and enumerations) are at the attribute level. EML docs have 3 levels: Dataset, Entity, and Attribute. Things at the attribute level require all three: (di, ei, ai), as you noted (whereas keywords and sites only have di). 

I prefer non-numeric missing value codes. If I use -1 or 99999 there is a chance that a script reading the file will process those as values, not as codes. Hopefully a human will notice and intervene. But if we use non-numeric codes then a code not recognizing these will bomb. Bombing is better than silently misinterpreting. Languages have built in codes (like dot for SAS, NA for R, Inf and NaN for Matlab) but data providers have no say what language data users employ. 

Ideally, the code reading the data gets its ingest code from pastaprog or similar metadata-reading auto-code-writing software. Those read the missing value codes and apply them. For example, the ECC does not throw a data load error for a defined string code in a numeric column. It will if the missing value code is NOT defined. I love the checker.

If we do introduce some cross-reference tables with the (di, ei, ai) plus the item's id, let's decide on a pattern of naming those (di, ei, ai) indices. I apologize for messing that up when I ported Metabase. I use a different index for ei in different tables. My bad. You will do better!

**Comment by scelmendorf** [comment]
Sounds good to me - I think it can follow the same structure (and R code to process) as the EMLAttributeCode definition table. I am also in favor of non-numeric missing value codes to avoid people not reading the metadata and inadvertently averaging in some of those -9999s. I love the checker too as it tells me when there is a missing value code in a numeric field that hasn't been documented (happens all the time!)

**Comment by twhiteaker** [comment]
I was raised on "use numeric codes in numeric fields," but I can see the merit in using text codes to some degree to avoid accidentally averaging in -9999s.  A script might fail if text codes are used, thereby alerting the user, though Excel ignores text when taking an average so in that case the -9999 might actually be better because the result will look wonky.

More tidbits:
CUAHSI ODM requires numeric codes.

[DataONE suggests using numeric codes as a best practice.](https://www.dataone.org/best-practices/identify-missing-values-and-define-missing-value-codes)

But that's just philosophy.  The [suggested approach](https://github.com/lter/LTER-core-metabase/issues/38#issuecomment-483437209) for supporting multiple codes sounds fine to me.

**Comment by mobb** [comment]
+1 for numeric codes in numeric fields.

**Comment by atn38** [comment]
So, I poked around: the EML R package doesn't support multiple missing codes per attribute ([opened an issue on their github repo](https://github.com/ropensci/EML/issues/268)), and EMLassemblyline doesn't either -- makes sense because Colin relies on the EML R package under the hood. So to make this happen (and I'm for making it happen), we need to update three pieces: metabase schema, [mb2eml](https://github.com/atn38/rMetabase2eml), and EML R itself. 

@scelmendorf, how have you been storing your multiple codes and/or writing them into EML?

**Comment by scelmendorf** [comment]
I put them in as a sem-colon separated list in the missingValueCode to remind myself to go back and deal with this database-wise later. I was too lazy to write code to actually parse out list stored in cell (plus, this is a bad idea because typos are prevalent), so I just manually coded it up for the handful of datasets I've had so far that has it, i.e. build up the missing code list manually list(code = 'lalal', codeExplanation = 'singing') and parking that in to the eml$dataset$DataTable$attributeList$attribute$missingValueCode list before writing out. It's fairly manual... I don't recommend it. But it does work and a step above writing the eml out to xml and then editing it by hand because at least you have traceability on what you did!

**Comment by mbjones** [comment]
Note the discussion in https://github.com/ropensci/EML/issues/268 which is proposing a new parameter for a table of missingValueCodes to `EML::set_attributes`.  Comments appreciated there on what is being proposed for the EML package.

**Comment by mobb** [comment]
Interesting discussion. Also good to see that sometimes, folks do think that a more complex data model is warranted.

**Comment by mobb** [comment]
Here are the xpaths are repeatable at the attribute level: 
Practical, and used:
enumeratedDomain (multiple code def pairs)
missingValueCode (multiple flags per attribute)

practical and probably useful, but not often used. So might consider for future
accuracy/quantitativeAttributeA...

not practical (or not part of a profile LTER is likely to use)
attributeLabel
storageType

**Comment by jeanetteclark** [comment]
This feature got merged into EML this morning. Feel free to comment over there if you find issues. I hope you find it helpful! I want the EML package to be as useful as possible for people, so feel free to add more issues if you run into something that seems harder than it should be.

@mobb Thanks for giving that list - I was wondering what other repeatable attribute level fields there were.

**Comment by mobb** [comment]
@jeanetteclark , I added one more to the list, for EML 2.2: annotation

That one is gonna be fun.

**Comment by atn38** [comment]
closed because PR #43 was accepted.
