### ISSUE TITLE
move reference tables to separate schema?

### ISSUE THREAD

**Issue by atn38** [lter/LTER-core-metabase#40]
As we add more tables and cross-reference tables to the core schema (`lter_metabase`), might we consider moving fairly immutable lookup tables (eg. `EMLNumberTypeList` and `MeasurementScaleDomains`) to a separate schema? This may (1) help with clutter and (2) clarify the roles of the different schemas.

`pkg_mgmt` (which I haven't looked into as much) also has a number of lookup tables starting with `cv_`. Some of these are specific to SBC/MCR, but some, eg. `cv_cra` for LTER core research areas, might be useful to add into a schema of lookup tables.

**Comment by atn38** [comment]
@mobb @gastil should we re-visit this in light of our discussion on Friday?

**Comment by gastil** [comment]
Writing this note now so I will remember, but not today's task. Yes, we should soon discuss our criteria for lumping and/or splitting objects in schemas (objects being tables, views, sequences, triggers, functions, and stuff. Mostly tables and views.) 

I am going to purposefully list extremes we likely will not adopt, just to show the range of options.

Option split_by_topic: 

to group objects relating to a topic, separating schemas for 
- biblio
- taxon
- geographic
- parties (people, orgs and related things)
- keywords
- annotation

 ... then ... and the following I would be less likely to split out... 
- dataset level things currently in DataSet
- methods
- dataTable things (file, vars, missValues, enums, ...), 

... then the things already split out, or ones to come like those...
- pkg_mgmt
- mb2eml (perl)
- mb2eml_r

Option split_by_objectType:

- one schema for parent tables that control vocabs, the tables starting with cv_ and the tables which would start with cv_ were we naming them ourselves rather than inheriting names from GCE.
- one schema for many-to-many xrefs
- one schema for leaf children (that just have one parent and no children)

I do not like the split-by-object-type because if I am working on filling in a child table I would wan the parent table handy. I realize this is an artifact of direct-db-editing. But that is where we are for now, and for some time. 

GCE did have taxon, biblio, projects, and a few other schemas that we do not currently have in lter_core_mb but that are in my "full" schema. Not that I use them, much. But I'm accustomed to them.

It is easy to think why have a schema for just one or two tables. Then they grow families of tables around them. It is much easier to split a schema now than later. I do not know if I can move a table from one schema to another on-the-fly, live. I could test that. 

I am not suggesting having 2 levels of splitting. 

It can be awkward (although possible) to have FKs across schemas bi-directional. But not awkward uni-directional. Views should are expected to query from multiple schemas.

**Comment by gastil** [comment]
One goal of splitting the lter_metabase schema was to sort tables by user interaction level. By renaming the tables, they now sort into those 3 categories, obviating the need to split that schema.
