### ISSUE TITLE
provide optional script to DELETE example data

### ISSUE THREAD

**Issue by atn38** [lter/LTER-core-metabase#64]
We decided to provide a one-file install script that includes everything. We think it's a good way to show people how to use metabase. If people want to delete the example data while keeping controlled vocabs and suggested content (Thesauri and Taxonomic Providers), Gastil will write an optional SQL script for them.

**Comment by gastil** [comment]
patch 26_delete_example_datasets.sql deletes the four examples provided (at least as of now). This is an OPTIONAL patch. It does not delete the EML_ or List_ tables' rows that come with initial installation. I expect to make another patch for the List_ but perhaps not for the EML_ unless someone suggests otherwise. Will close this issue after List_ script is done.

**Comment by gastil** [comment]
patches 28_delete_all_rows_from_ListTables.sql and 29_delete_all_rows_from_EMLTables.sql complete this issue. Again, do not apply these "patches" as routine. These are only for special cases when empty parent tables are desired.

Do not make an OBF with 26, 28, or 29 applied.
