### ISSUE TITLE
use ListMissingCodes for enumeration codes as well

### ISSUE THREAD

**Issue by atn38** [lter/LTER-core-metabase#96]
annoyance: no dictionary for attribute enumeration yet, so have to duplicate rows every time for our standard "habitat" columns that only ever take three values.

observation: the structure for attribute enumeration-type codes ("m" means male "f" means female) is essentially the same as missing code: all attribute level, each code has the code and the definition.

IDEA: rename `ListMissingCodes` to `ListCodes` and use it for both kind of codes. The `DataSet` tables would still be separate.

**Comment by gastil** [comment]
Seems like a good idea. The changes will propagate thru the SQL DDL. Off hand I am not thinking of any problems. I might suggest adding a column where one could (optionally?) designate a code as intended for enum vs intended for missing values. That would make it easier to filter when you want to see what codes you used for Beaufort Sea Scale, for example. And when we load from EML2MB that column could be filled by what xpath the (code, definition) pair came from. 

I noticed an xpath Ive never used while mapping the EML to MB. It was for saying where one got an enumeration, the element <source>, sibling to code and definition. Not cpu, so we do not have to put it in mb. But we could, if we wanted to. I mention this because missing value does not have that eml xpath. Missing values do not have a source (at least not in eml2.1).

**Comment by atn38** [comment]
> It was for saying where one got an enumeration, the element , sibling to code and definition.
You mean 'source'? we just discovered it yesterday too.

**Comment by twhiteaker** [comment]
As metabase has been stable for a while and is working well, I suggest that before you make this change, create a release of the current version (if you have not already done so) of Metabase, and then create a release of MetaEgress which indicates the version of Metabase to which it applies.

**Comment by gastil** [comment]
There is a pending stack of modifications waiting for me to code, test and commit them. Has been since last summer. Some are quite significant, such as reinstating pkg_mgmt.pkg_state as parent of DataSet. Once those are in, then yes time to consider releasing a version. The EML2MB will go with the next version, not the current config. 

What An suggests in this issue here is to use one table as cv (parent) for both MissingValue codes and Enumeration codes, and possibly to add a column to handle source if anyone plans to use that. (Seems useful and not significant code bloat.)  The only code changes would be changing a table name, which cascades, and adding a column, which is backward compatible. So this particular issue would not be version-scale, just a patch.

**Comment by twhiteaker** [comment]
The database modifications would make the current version of MetaEgress incompatible.  If we make releases for Metabase and MetaEgress, it makes it easier to identify which version goes with which.  In MetaEgress, you also may want to check that you're hooked up to a compatible version of Metabase if you haven't already done so.

**Comment by gastil** [comment]
Hang on - why would a change of table name or addition of a column break MetaEgress? The VIEW query would change with the table name change, but even that would cascade. The modified Metabase would not change its outward exposure. That is the point of using VIEWs as an abstraction layer. Great example of that, actually. 

MetaEgress, I trust, gets its content from Metabase not from TABLEs, but only from VIEWs.  The output of the VIEW does not need to change.

Here is the relevant view:
```
CREATE OR REPLACE VIEW mb2eml_r.vw_eml_missingcodes AS
 SELECT d."DataSetID" AS datasetid, d."EntitySortOrder" AS entity_position, 
    d."ColumnName" AS "attributeName", e."MissingValueCode" AS code, 
    e."MissingValueCodeExplanation" AS definition
   FROM lter_metabase."DataSetAttributeMissingCodes" d
   JOIN lter_metabase."ListMissingCodes" e ON d."MissingValueCodeID"::text = e."MissingValueCodeID"::text
  ORDER BY d."DataSetID";
```
The part that changes is in the JOIN clause. s/Missing//. The output result set is unchanged.

Maybe An also add a view for enumeration. So if MetaEgress depends on there existing a new VIEW, then yes I see being able to specify the patch level of the revision. It's still a patch, not a major version.

**Comment by twhiteaker** [comment]
Oh, you could be right, and that would be awesome!

**Comment by atn38** [comment]
Confirm that MetaEgress gets its stuff from VIEWs not tables. It doesn't
care what the DDL for the VIEWs are, just that the view name and the view
column names remain the same.

There's already a view for enumeration, vw_eml_attributecodedefinition. It
really is a copy of DataSetAttributeEnumeration, which IMO we're keeping.

The most involved code would be for migration and consolidation of the
code-def pairs already in DSAttributeEnumeration and moving them into
ListCodes.

**Comment by gastil** [comment]
An, want me to write the “select into” sql?  Send a pg-dump for me to use as testing please. Or you want to write it?

**Comment by atn38** [comment]
Dump sent. I'll take a stab as well.

**Comment by gastil** [comment]
here is my proposed patch:
```
-- This patch renames the parent table for missing value codes to be generalized to also hold enumeration code-defintion pairs.
ALTER TABLE lter_metabase."ListMissingCodes" RENAME TO "ListCodes";
ALTER TABLE lter_metabase."ListCodes" RENAME "MissingValueCodeID" TO "CodeID";
ALTER TABLE lter_metabase."ListCodes" RENAME "MissingValueCode" TO "Code";
ALTER TABLE lter_metabase."ListCodes" RENAME "MissingValueCodeExplanation" TO "CodeExplanation";

--The code is max 20 characters so cannot use column names.
--Two codes: VALID and QM are re-used so I appended the length of their definition, just to
-- get these into the table. Then you can manually edit as desired.

INSERT INTO lter_metabase."ListCodes"
SELECT 
CASE "Code" 
  when 'VALID' then max('enum.'||"Code"||length("Definition")::text)
  when 'QM' then max('enum.'||"Code"||length("Definition")::text)
  else max('enum.'||"Code")
END AS "CodeID",
"Code", "Definition" AS "CodeExplanation"
FROM lter_metabase."DataSetAttributeEnumeration"
group by "Code", "Definition" 
```

-- Not all the pieces here yet.

**Comment by atn38** [comment]
see my proposed patch on migration branch. Ran fine on BLE mb without errors and gave desired results. 

I went with scenario B re:`DataSetAttributeEnumeration` as IMO that's a cleaner and better end result:

![image](https://user-images.githubusercontent.com/42045942/76012802-84ad7e00-5edc-11ea-9ddb-ff7b651d30b0.png)

**Comment by gastil** [comment]
Glad that worked on your production installation of core-mb. 

Now, initial the box below to acknowledge that you can see that my hack to append the length of characters in the definition to the enum code for the ID is (A) a totally irresponsible hack which in future allow redundancy and (B) works; done is better than perfect. 

- [ ] I, An, acknowledge that Gastil hacked core-mb and promise not to shame her for it.

;)

**Comment by atn38** [comment]
Look! We did it. Closing now.
